import React from 'react';
import type { ChainedFormula } from '../types';

interface FormulaChainProps {
  chain: ChainedFormula[];
  onRemove: (id: string) => void;
  onSuggestNextStep: () => void;
  suggestions: string[] | null;
  isSuggesting: boolean;
  suggestionError: string | null;
  onSuggestionClick: (suggestion: string) => void;
  onAnalyzeChain: () => void;
  isAnalyzingChain: boolean;
  chainAnalysis: string | null;
  chainAnalysisError: string | null;
  onClearAnalysis: () => void;
}

const FormulaChain: React.FC<FormulaChainProps> = ({ 
  chain, 
  onRemove,
  onSuggestNextStep,
  suggestions,
  isSuggesting,
  suggestionError,
  onSuggestionClick,
  onAnalyzeChain,
  isAnalyzingChain,
  chainAnalysis,
  chainAnalysisError,
  onClearAnalysis
}) => {
  if (chain.length === 0) {
    return null; // Don't render anything if the chain is empty
  }

  const handleExportLaTeX = () => {
    const escapeLaTeX = (str: string) => {
      if (!str) return '';
      return str
        .replace(/&/g, '\\&')
        .replace(/%/g, '\\%')
        .replace(/\$/g, '\\$')
        .replace(/#/g, '\\#')
        .replace(/_/g, '\\_')
        .replace(/{/g, '\\{')
        .replace(/}/g, '\\}')
        .replace(/~/g, '\\textasciitilde{}')
        .replace(/\^/g, '\\textasciicircum{}')
        .replace(/\\/g, '\\textbackslash{}');
    };

    let latexString = `\\documentclass{article}
\\usepackage{amsmath}
\\usepackage{geometry}
\\usepackage{bera}
\\geometry{a4paper, margin=1in}
\\title{FormulaForge Chain Export}
\\author{Generated by FormulaForge}
\\date{\\today}

\\begin{document}
\\maketitle

\\section*{Chain Overview}
This document outlines a chain of formulas generated by FormulaForge.

\\hrulefill
\\vspace{1em}

`;

    chain.forEach((item, index) => {
      latexString += `\\section{Step ${index + 1}: ${escapeLaTeX(item.formula.formulaName)}}
\\subsection*{Formula}
\\[
${item.formula.formulaString}
\\]

\\subsection*{Explanation}
${escapeLaTeX(item.formula.explanation)}

\\subsection*{Result}
\\begin{verbatim}
${item.result}
\\end{verbatim}

\\vspace{1em}
\\hrulefill
\\vspace{1em}

`;
    });

    latexString += `\\end{document}`;

    const blob = new Blob([latexString], { type: 'text/x-latex' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'formula_chain.tex';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const isAnalyzeDisabled = chain.length < 2 || isAnalyzingChain;

  return (
    <div className="p-4 md:p-6 bg-slate-800/50 rounded-lg border border-slate-700">
      <h3 className="text-xl font-semibold text-cyan-400 mb-4">Formula Chain</h3>
      <ul className="space-y-3">
        {chain.map((item, index) => (
          <li key={item.id} className="p-3 bg-slate-900/70 rounded-md border border-slate-700 flex justify-between items-center">
            <div className="flex-1 overflow-hidden">
              <div className="text-xs text-slate-500 font-semibold tracking-wider uppercase">Step {index + 1}</div>
              <p className="text-slate-300 font-medium truncate" title={item.formula.formulaName}>
                {item.formula.formulaName}
              </p>
              <p className="text-cyan-400 font-mono text-sm truncate" title={item.result}>
                Result: {item.result}
              </p>
            </div>
            <button
              onClick={() => onRemove(item.id)}
              className="ml-4 px-2 py-1 text-xs bg-red-800 text-red-200 rounded hover:bg-red-700 transition-colors focus:outline-none focus:ring-2 focus:ring-red-500"
              aria-label={`Remove ${item.formula.formulaName} from chain`}
            >
              Remove
            </button>
          </li>
        ))}
      </ul>

      {/* Chain Actions */}
      <div className="mt-4 pt-4 border-t border-slate-700 space-y-4">
        <div>
          <h4 className="text-lg font-semibold text-slate-300 mb-3">Chain Actions</h4>
          <div className="flex flex-col sm:flex-row gap-2">
            <button
              onClick={onAnalyzeChain}
              disabled={isAnalyzeDisabled}
              className="flex-1 inline-flex items-center justify-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-teal-600 hover:bg-teal-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-slate-800 focus:ring-teal-500 transition-colors disabled:bg-slate-600 disabled:cursor-not-allowed"
              title={chain.length < 2 ? "Requires at least 2 steps in the chain" : "Analyze chain consistency"}
            >
              {isAnalyzingChain ? (
                <svg className="animate-spin -ml-1 mr-2 h-5 w-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path></svg>
              ): (
                <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-6 9l2 2 4-4" /></svg>
              )}
              {isAnalyzingChain ? 'Analyzing...' : 'Analyze Consistency'}
            </button>
            <button
              onClick={handleExportLaTeX}
              className="flex-1 inline-flex items-center justify-center px-4 py-2 border border-slate-600 text-sm font-medium rounded-md shadow-sm text-slate-300 bg-slate-700 hover:bg-slate-600 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-slate-800 focus:ring-cyan-500 transition-colors"
            >
              <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" /></svg>
              Export as LaTeX
            </button>
          </div>
        </div>
        
        {(chainAnalysis || chainAnalysisError) && (
          <div className="relative p-4 bg-slate-900/70 rounded-md border border-slate-700">
             <button onClick={onClearAnalysis} className="absolute top-2 right-2 text-slate-500 hover:text-slate-300" aria-label="Close Analysis">
                <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" /></svg>
            </button>
            {chainAnalysis && (
              <div>
                <h5 className="text-md font-semibold text-teal-400 mb-2">Chain Analysis Result</h5>
                <p className="text-sm text-slate-400 whitespace-pre-wrap">{chainAnalysis}</p>
              </div>
            )}
            {chainAnalysisError && (
              <div className="text-sm text-red-400">
                <p><strong className="font-semibold">Analysis Error:</strong> {chainAnalysisError}</p>
              </div>
            )}
          </div>
        )}
      </div>

      {/* Next Step Suggestions */}
      <div className="mt-4 pt-4 border-t border-slate-700">
        <h4 className="text-lg font-semibold text-slate-300 mb-3">Next Step</h4>
        {!suggestions && !isSuggesting && !suggestionError && (
             <button
              onClick={onSuggestNextStep}
              className="w-full inline-flex items-center justify-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-slate-800 focus:ring-indigo-500 transition-colors"
            >
                💡 Suggest Next Step
            </button>
        )}
       
        {isSuggesting && (
             <div className="flex items-center justify-center p-2">
                <svg className="animate-spin h-6 w-6 text-cyan-500" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                  <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                  <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                </svg>
                <span className="ml-3 text-slate-400">Thinking...</span>
            </div>
        )}

        {suggestionError && (
            <div className="p-3 bg-red-900/50 text-red-300 border border-red-700 rounded-md text-sm">
                <p><strong className="font-semibold">Error:</strong> {suggestionError}</p>
                <button onClick={onSuggestNextStep} className="mt-2 text-xs text-cyan-400 hover:underline">Try again</button>
            </div>
        )}

        {suggestions && (
             <div className="space-y-2">
                <p className="text-sm text-slate-400">Here are some ideas for your next step:</p>
                {suggestions.map((idea, index) => (
                    <button
                        key={index}
                        onClick={() => onSuggestionClick(idea)}
                        className="w-full text-left p-3 bg-slate-700/50 hover:bg-slate-700 rounded-md text-slate-300 transition-colors text-sm"
                    >
                        {idea}
                    </button>
                ))}
            </div>
        )}
      </div>
    </div>
  );
};

export default FormulaChain;
